# Generated by Django 5.2.7 on 2025-12-26 16:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=150)),
                ('s_grade', models.CharField(choices=[('A', 'A (4.0)'), ('A-', 'A- (3.7)'), ('B+', 'B+ (3.3)'), ('B', 'B (3.0)'), ('B-', 'B- (2.7)'), ('C+', 'C+ (2.3)'), ('C', 'C (2.0)'), ('C-', 'C- (1.7)'), ('D+', 'D+ (1.3)'), ('D', 'D (1.0)'), ('F', 'F (0.0)')], max_length=150)),
                ('s_credit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(6)])),
                ('s_count', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
