# Generated by Django 5.2.7 on 2025-12-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0002_details_delete_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='s_count',
        ),
    ]
