# Generated by Django 5.2.7 on 2026-01-03 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0003_remove_details_s_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='s_credit',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='details',
            name='s_grade',
            field=models.CharField(blank=True, choices=[('A', 'A (4.0)'), ('A-', 'A- (3.7)'), ('B+', 'B+ (3.3)'), ('B', 'B (3.0)'), ('B-', 'B- (2.7)'), ('C+', 'C+ (2.3)'), ('C', 'C (2.0)'), ('C-', 'C- (1.7)'), ('D+', 'D+ (1.3)'), ('D', 'D (1.0)'), ('F', 'F (0.0)')], max_length=150),
        ),
        migrations.AlterField(
            model_name='details',
            name='s_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
