# Generated by Django 5.2.7 on 2026-01-03 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0004_alter_details_s_credit_alter_details_s_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='s_credit',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='details',
            name='s_name',
            field=models.CharField(max_length=150),
        ),
    ]
